name: ASU Design System Package Update CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "@asu:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
          mkdir -p $GITHUB_WORKSPACE/packages
          cd $GITHUB_WORKSPACE/packages
          npm install @asu/component-header
      - name: Update files
        run: |
          cd $GITHUB_WORKSPACE/repo
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          rm -rf component-header
          mv $GITHUB_WORKSPACE/packages/node_modules/\@asu/component-header .
          git add .
          git update-index --refresh 
          git diff-index --quiet HEAD -- || ( git commit -m "Updating ASU Design System from source - $(date)" && git push )
